dist: xenial
language: go
sudo: true
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
install:
  # install brotli
  - git clone https://github.com/google/brotli.git
  - cd brotli
  - mkdir out && cd out
  - ../configure-cmake
  - make
  - make test
  - sudo mkdir -p /usr/local/bin/brotli
  - sudo make install
  - cd ../..
  # install go dependencies
  - go get -u golang.org/x/lint/golint
  - go get -v ./...
script:
  - golint
  - sudo go test -v
  - sudo cd benchmark && go build && ./benchmark
