language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
before-install:
  - sudo apt-get update
  - sudo apt-get install brotli -y
install:
  - go get -u golang.org/x/lint/golint
  - go get -v ./...
script:
  - golint
  - go test -v
  - cd benchmark && go build && ./benchmark
